import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "../globals.css";
import JotaiProviders from "./jotai-provider";
import { getMessages } from "next-intl/server";
import { ClerkProvider } from "@clerk/nextjs";
import { viVN } from "@clerk/localizations";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  return (
    <html lang="en">
      <body>
        <ClerkProvider localization={viVN}>
          <NextIntlClientProvider messages={messages}>
            <JotaiProviders>{children}</JotaiProviders>
            <Toaster richColors position="top-right" />
          </NextIntlClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
