name: k8s
on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ecommerce-system-frontend
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

## checks out the commit made to the project
      - name: Checkout code
        uses: actions/checkout@v4

## logins to ghcr
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          username: ngophuocloi
          password: ${{ secrets.DOCKER_PASSWORD }}

## builds and pushes the image to ghcr
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ngophuocloi/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
#   Test-on-cluster:
#     runs-on: ubuntu-latest
#     steps:
# ## starts the cluster
#       - name: Testing on a k8s Kind Cluster
#         uses: helm/kind-action@v1.4.0
# ## makes sure cluster is up and running
#       - run: |
#           kubectl cluster-info
#           kubectl get nodes
#       - name : Preparing cluster for kube-ez
# ## Commands that setup the cluster as per my project needs
#         run: |
#           kubectl apply -f https://raw.githubusercontent.com/kitarp29/kube-ez/main/yamls/sa.yaml
#           kubectl apply -f https://raw.githubusercontent.com/kitarp29/kube-ez/main/yamls/crb.yaml
#           kubectl run kube-ez --image=ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} --port=8000
#           sleep 20
#           kubectl get po
#           kubectl port-forward kube-ez 8000:8000 &>/dev/null &
#           sleep 5
#           kubectl port-forward kube-ez 8000:8000 &>/dev/null &
#       - run: |
#           curl -i http://localhost:8000/